version: "3.8"

networks:
  app_net:

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - app_net
    command: python app.py
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build: ./client
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app_net
    command: python client.py
    restart: on-failure
